API Documentation Update
vertigis/studio-dev-center pull request #63
Opened 2024-04-15 16:35 UTC by yonabystedt

This PR:
- Updates Docusaurus and fixes Typescript integration.
- Fixed the automatic links to page sections (the hashtag that pops up on hover).
- Splits the commands, operations and events page into three: Commands & Operations, Events, Argument Definitions.
- Argument Definitions also hosts the definitions hosted previously on the Components and Services page.
- Added `esri-rest-api` definitions to the Arguments page. These are frequently referenced and undocumented elsewhere (!). While these entries often link out to Web Map/Scene docs and are meant to represent the same API there are some differences in implementation, so this will hopefully clear up some confusion.
- Added local caching to speed up the very large Argument Definitions page. The data will be refreshed if older than 1 day.
- Adds a API Objects page that documents `Features`, `FeatureSources` and `*Extensions`. The audience is assumed to be someone building a command chain that might encounter these, so this documentation is *not* complete. It's expected that we'll add some `typedoc` or similar output added later to assist coders using the API directly.
- Concatenated a bunch of feature types into a single `Features` listing that links to the new page. This actually better represents what you'd see if you looked at the signatures of these items in our codebase.
- Added support for Markdown throughout all descriptions. Code blocks and tables added to JSDoc comments should be rendered correctly, though you'll need Fiddler and a modified file I can provide to test this right now.

The PR does not do anything to fix navigation, as this will require some more refactoring of the schema download step, and it isn't clear how to fit this in the Docusaurus project. It might have to be written as a plugin.

2024-04-15 17:52 UTC, rcooney requested changes
What do we want to do with the old Web and mobile `api-commands-operations-events.mdx` pages? They aren't in the TOC now, but they will still load (but they are disconnected). Things likely link to them. 

Options:
- We could make those pages to do a `<meta http-equiv="refresh"` to the new page?
- We could use something like https://docusaurus.io/docs/api/plugins/@docusaurus/plugin-client-redirects

2024-04-16 16:13 UTC, yonabystedt commented
@rcooney I managed to find a working strategy for redirecting links to those pages, so this should be a totally seamless change now.

2024-04-16 16:27 UTC, rcooney requested changes

2024-04-16 16:27 UTC, rcooney commented on docs/web/api-commands-operations-events.mdx
> +
I think we should restore these headers to something like this that will:
- Show something formatted if the page is slow. Currently you see the filename as the title.
- Keep this page out of the sitemap
- Hide the edit link

```
---
title: Redirecting...
custom_edit_url: null
unlisted: true
---
```

2024-04-16 18:33 UTC, rcooney approved these changes

2024-04-23 16:55 UTC, merged